export interface VFSFile {
  content: string;
}

export interface VFS {
  [path: string]: string;
}

export function parseVFS(output: string): VFS {
  const vfs: VFS = {};
  
  // Split by <file path=" to find all starts
  const fileParts = output.split(/<file path="/gi);
  
  // First part is usually conversational text before the first tag
  // Subsequent parts start with the path name
  for (let i = 1; i < fileParts.length; i++) {
    const part = fileParts[i];
    const pathEndIndex = part.indexOf('">');
    if (pathEndIndex === -1) continue;
    
    const rawPath = part.substring(0, pathEndIndex);
    const normalizedPath = rawPath.startsWith('/') ? rawPath.slice(1) : rawPath;
    
    let content = part.substring(pathEndIndex + 2);
    
    // Check if tag is closed, if so, strip the closing tag and anything after
    const tagEndIndex = content.toLowerCase().indexOf('</file>');
    if (tagEndIndex !== -1) {
      content = content.substring(0, tagEndIndex);
    }
    
    // Clean up content (remove backticks if AI added them)
    let cleanContent = content.trim().replace(/^```[a-z]*\n/i, '').replace(/\n```$/i, '').trim();
    
    // If tag is not closed, the last part might be malformed (truncated)
    if (tagEndIndex === -1) {
      // Very basic fix: if the last char is < or partly written tag, try to strip it
      // or at least ensure it doesn't end in an open bracket if possible.
      // Better yet: if it ends in something like </h2, strip the partial tag.
      cleanContent = cleanContent.replace(/<[^>]*$/g, ''); 
    }

    vfs[normalizedPath] = cleanContent;
  }

  // Fallbacks if no tags found (standard output or single file)
  if (Object.keys(vfs).length === 0 && output.trim()) {
    const cleanOutput = output.replace(/^```[a-z]*\n/i, '').replace(/\n```$/i, '').trim();
    // For vanilla JS, if it looks like HTML, put it in index.html, otherwise script.js
    if (cleanOutput.includes('<!DOCTYPE html>') || cleanOutput.includes('<html')) {
      vfs['index.html'] = cleanOutput;
    } else {
      vfs['script.js'] = cleanOutput;
    }
  }

  return vfs;
}

export const getAppStructure = (vfs: Record<string, string>) => {
  const files: Record<string, { code: string }> = {};

  // Map VFS to Sandpack file structure
  Object.entries(vfs).forEach(([path, content]) => {
    const lowPath = path.toLowerCase().trim();
    // Aggressively filter out framework noise and unwanted files
    if (
        lowPath.includes('package.json') || 
        lowPath.includes('package-lock.json') ||
  
        lowPath.includes('vite.config') ||
        lowPath.includes('tailwind.config') ||
        lowPath.includes('index.js')
    ) {
        return;
    }
    const sandpackPath = path.startsWith('/') ? path : `/${path}`;
    files[sandpackPath] = { code: content };
  });

  // vanilla template needs an entry point to not crash, 
  // but we can make it a hidden / empty dummy if not generated by AI
  if (!files['/index.js']) {
    files['/index.js'] = { code: '// Bootstrapping...' };
  }

  // Ensure index.html exists
  if (!files['/index.html'] && !files['index.html']) {
    files['/index.html'] = { code: DEFAULT_FILES["index.html"] };
  }

  return files;
};

export const DEFAULT_FILES = {
  "index.html": `<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Website</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body, html { height: 100%; margin: 0; padding: 0; }
        #app { min-height: 100%; width: 100%; }
    </style>
</head>
<body class="bg-gray-50 text-gray-900 h-full">
    <div id="app" class="flex items-center justify-center h-full">
        <div class="text-center">
            <h1 class="text-4xl font-bold text-gray-300 mb-4 animate-pulse">Building your vision...</h1>
            <p class="text-gray-400">Your website is being generated in real-time.</p>
        </div>
    </div>
</body>
</html>`
};
